### ISSUE TITLE
開発開始時の環境構築

### ISSUE THREAD

**Issue by KaoruTsunekawa** [ngpool/CareConne#1]
- 開発開始時の環境構築を実施する
- Dockerでコンテナ化
- docker-composeでまとめてコンテナを起動できるようにする
- コンテナ
  - サーバ (APIの受け口)
  - DB (PostgreSQL)

**Comment by yudaiyagi** [comment]
@KaoruTsunekawa さん
一旦構築のものはdevelopにプッシュしたのでクローズします。

**Comment by yagi-team** [comment]
@KaoruTsunekawa さん
構築完了のものGitにプッシュしました。
